project_id = "ayjykrmpiatjerfxaykd"

[functions.asaas-webhook]
verify_jwt = false

[functions.get-kb-file-url]
verify_jwt = false

[functions.cleanup-old-messages]
verify_jwt = false

[functions.delete-own-account]
verify_jwt = false
